version: '3.4'
services:
  prometheus:
    image: prom/prometheus:v2.37.0
    restart: always
    volumes:
      - ./prometheus/:/etc/prometheus/
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - 9090:9090

  grafana:
    image: grafana/grafana:9.0.5
    restart: always
    ports:
      - 3060:3000
    depends_on: ['prometheus']
