version: 2.1

orbs:
  python: circleci/python@1.5.0

jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.8
    resource_class: medium
    parallelism: 2

    steps:
      - checkout

      # TODO: Add Python version (matrix strategy)
      - restore_cache:
          name: Restore cached venv
          keys:
            - v1-pypi-py3.8-{{ checksum "requirements.txt" }}
            - v1-pypi-py3.8-

      - run:
          name: Update & Activate venv
          command: |
            python -m venv env/
            . env/bin/activate
            pip install -r requirements.txt

      - save_cache:
          name: Save cached venv
          paths:
            - "env/"
          key: v1-pypi-py3.8-{{ checksum "requirements.txt" }}

      - run:
          name: Install Bittensor
          command: |
            . env/bin/activate
            pip install -e .

      - run:
          name: Instantiate Mock Wallet & Protos
          command: |
            . env/bin/activate
            ./scripts/create_wallet.sh && ./scripts/build_protos.sh

      - restore_cache:
          name: Restore cached test timings
          keys:
            - test-timings-v1-{{ .Branch }}
            - test-timings-v1-

      - run:
          name: Unit Tests
          command: |
            mkdir -p test-timings/
            . env/bin/activate
            pytest -n2 --durations=0 --verbose --junitxml=test-results/unit_tests.xml \
            --splits $CIRCLE_NODE_TOTAL --group $((CIRCLE_NODE_INDEX + 1)) \
            --splitting-algorithm least_duration --store-durations --durations-path test-timings/.unit_test_durations_$CIRCLE_NODE_INDEX \
            tests/unit_tests/
            

      - run:
          name: Integration Tests
          command: |
            . env/bin/activate
            pytest -n2 --durations=0 --verbose --junitxml=test-results/integration_tests.xml \
            --splits $CIRCLE_NODE_TOTAL --group $((CIRCLE_NODE_INDEX + 1)) \
            --splitting-algorithm least_duration --store-durations --durations-path test-timings/.integration_test_durations_$CIRCLE_NODE_INDEX \
            tests/integration_tests/

      - save_cache:
          name: Save cached timings
          paths:
            - "test-timings/"
          key: test-timings-v1-{{ .Branch }}

            
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results

workflows:
  pre-pr:
    jobs:
      - build-and-test
