version: 2.1

orbs:
  python: circleci/python@1.5.0

jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.8
    resource_class: medium
    parallelism: 4

    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip

      - run:
          name: Install bittensor
          command: pip install -e .

      - run:
          name: Instantiate wallet & protos
          command: ./scripts/create_wallet.sh && ./scripts/build_protos.sh

      - run:
          name: Run tests
          command: |
            set -e
            TEST_FILES=$(circleci tests glob "tests/**/test_*.py" | circleci tests split --split-by=timings --timings-type=filename)
            mkdir -p test-results
            cp tests/pytest.ini . # workaround to fix pathing issues with pytest.
            pytest -c pytest.ini --durations=0 --verbose --junitxml=test-results/junit.xml $TEST_FILES

      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results

workflows:
  pre-pr:
    jobs:
      - build-and-test
