---
global:
    scrape_interval: 10s
    evaluation_interval: 10s

scrape_configs:
    - job_name: monitoring
      static_configs:
        - targets:
            - localhost:9090

    - job_name: bittensor
      static_configs:
        - targets: 
            - ip-1:7091
            - ip-2:7091
            - ip-3:7091
