wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.33
    framework: huggingface
    huggingface_version: 4.5.1
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.8.10
    t:
      1:
      - 1
      - 11
      2:
      - 1
      - 11
      4: 3.8.10
      5: 0.10.33
      6: 4.5.1
      8:
      - 1
      - 5
