wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.0
    framework: huggingface
    huggingface_version: 4.5.1
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.11
    start_time: 1629401257
    t:
      1:
      - 1
      - 11
      2:
      - 1
      - 11
      4: 3.8.11
      5: 0.12.0
      6: 4.5.1
      8:
      - 5
axon:
  desc: null
  value:
    ip: '[::]'
    max_workers: 10
    maximum_concurrent_rpcs: 400
    port: 8091
miner:
  desc: null
  value:
    clip_gradients: 1.0
    learning_rate: 1
neuron:
  desc: null
  value:
    api_key: default
subtensor:
  desc: null
  value:
    chain_endpoint: null
    network: akatsuki
wallet:
  desc: null
  value:
    hotkey: default
    name: default
    path: ~/.bittensor/wallets/
wandb:
  desc: null
  value:
    directory: default
    name: default
    offline: false
    project: default
    run_group: default
    tags: default
